In [12]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [13]:
all_stat_w = np.load('all_stat_w.npz')
all_stat_wo = np.load('all_stat_wo.npz')

In [14]:
print all_stat_wo['ngroups'], all_stat_wo['ngals']

[66349 66983 67350 65492 66530 65791 65866 65259 65775 66619 67433 65988
 65733 66410 65747 65316 67183 66850 65537 66200] [103384 103124 103017 102906 101791 102183 102701 101809 101711 102948
 101843 102775 101616 103222 102296 102318 103300 103611 102480 102612]


In [17]:
all_stat_wo['gm'][0,1:]/(np.arange(299)+1)

array([49780,  9897,  3193,  1342,   680,   394,   277,   170,   130,
          82,    72,    39,    44,    33,    28,    29,     8,    16,
          14,     9,     7,    11,     6,    10,     5,     8,     5,
           5,     9,     2,     2,     2,     0,     5,     3,     2,
           3,     2,     1,     0,     0,     2,     1,     4,     1,
           0,     3,     1,     2,     0,     2,     0,     1,     1,
           0,     0,     1,     1,     0,     0,     0,     0,     0,
           0,     1,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     1,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     1,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,

In [19]:
all_stat_wo['cic3'][0]

array([    0, 56223, 23463,  9911,  4910,  2828,  1638,  1147,   860,
         577,   452,   309,   235,   197,   151,   127,    93,    69,
          51,    31,    19,    13,    16,     7,     9,     9,     8,
           7,     4,     5,     1,     1,     3,     2,     1,     0,
           3,     2,     0,     1,     1,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,

In [7]:
np.sum(all_stat_wo['gm'][0])

101770

In [14]:
all_stat_wo['param'][:3]

array([[  1.16832987,  13.30057559,   0.51081314,  10.52575539,
         12.04919897],
       [  1.12468963,  13.24743508,   0.26490527,  11.98903326,
         11.92589885],
       [  1.06433797,  13.19998706,   0.45002118,  12.35355223,
         11.99155001]])